# Generated by Django 5.0.6 on 2025-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50, unique=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_date', models.DateField()),
                ('fields', models.JSONField()),
            ],
        ),
    ]
